title: "BBC micro:bit a Smart Home"
numbering: True
footer: "Autor: M. Cápay a M. Bellayová (2022) v rámci projektu <a href='https://www.ucimeshardverom.sk/materialy/'>ucimeshardverom.sk/materialy</a> (Licencia CC BY-SA)"
